### ISSUE TITLE
Saving with an unsorted/unused import causes issues

### ISSUE THREAD

**Issue by fredrikaverpil** [charliermarsh/ruff-vscode#162] opened 2023-03-20 07:42 UTC
I've started having an issue where...
- unused imports are not automatically removed on save
- sorting imports causes the last line to get duplicated

I've seen both these issues before, but they were at some point fixed. I think this started sometime late last week (and I was on the early access version), but I'm not entirely sure.

My settings (an excerpt):

```jsonc
{
  "[python]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
      "source.fixAll.ruff": true
    }
  "python.formatting.provider": "black"
  },
}
```

Full settings json [here](https://github.com/fredrikaverpil/dotfiles/blob/main/vscode_settings.jsonc).

## Video

https://user-images.githubusercontent.com/994357/226275755-ce5783d9-0da3-4232-adbc-3f0374a4ceb6.mov

**Comment by JonathanPlasse** [comment] 2023-03-20 10:42
Thanks for your detailed report.
- This is a duplicate of #128

**Comment by fredrikaverpil** [comment] 2023-03-20 12:43
@JonathanPlasse ah ok!

Do you think the unused import not being autofixed is related?

**Comment by JonathanPlasse** [comment] 2023-03-20 13:00
Can you share you `pyproject.toml`?
Do you ignore `F401` errors?
If that is the case, it will not be auto-fixed.

**Closed** 2023-03-21 09:55 UTC

**Comment by JonathanPlasse** [comment] 2023-03-21 10:16
No problem.
